qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/LcpDbDataSource.java
package com.imyuanma.qingyun.lowcode.model;

import lombok.Data;
import java.util.Date;
import com.imyuanma.qingyun.interfaces.common.model.BaseDO;

/**
 * DB数据源实体类
 *
 * @author YuanMaKeJi
 * @date 2023-04-22 11:18:10
 */
@Data
public class LcpDbDataSource extends BaseDO {

    /**
     * 主键
     */
    private Long id;

    /**
     * 数据源编码
     */
    private String code;

    /**
     * 数据源名称
     */
    private String name;

    /**
     * 数据库类型
     */
    private String dbType;

    /**
     * 驱动类
     */
    private String driverClass;

    /**
     * 数据库连接
     */
    private String dbUrl;

    /**
     * 用户名
     */
    private String username;

    /**
     * 密码
     */
    private String password;

    /**
     * 备注
     */
    private String remark;



}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/LcpDict.java
package com.imyuanma.qingyun.lowcode.model;

import lombok.Data;
import java.util.Date;
import com.imyuanma.qingyun.interfaces.common.model.BaseDO;

/**
 * 字典表实体类
 *
 * @author YuanMaKeJi
 * @date 2022-12-04 23:42:56
 */
@Data
public class LcpDict extends BaseDO {

    /**
     * 主键
     */
    private Long id;

    /**
     * 字典编码,唯一
     */
    private String code;

    /**
     * 字典说明
     */
    private String name;

    /**
     * 类型,list:普通字典,tree:树结构字典
     */
    private String type;

    /**
     * 字典扩展属性
     */
    private String extInfo;

    /**
     * 系统内置字典标识
     */
    private String systemState;

    /**
     * 备注
     */
    private String remark;



}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/LcpDictItem.java
package com.imyuanma.qingyun.lowcode.model;

import lombok.Data;
import java.util.Date;
import com.imyuanma.qingyun.interfaces.common.model.BaseDO;

/**
 * 字典数据项实体类
 *
 * @author YuanMaKeJi
 * @date 2022-12-09 23:09:04
 */
@Data
public class LcpDictItem extends BaseDO {

    /**
     * 主键
     */
    private Long id;

    /**
     * 父节点code
     */
    private String parentCode;

    /**
     * 编码
     */
    private String code;

    /**
     * 说明
     */
    private String name;

    /**
     * 字典值
     */
    private String val;

    /**
     * 状态,yes:可用,no:禁用
     */
    private String status;

    /**
     * 扩展属性
     */
    private String extInfo;

    /**
     * 样式
     */
    private String style;

    /**
     * 字典编码
     */
    private String dictCode;

    /**
     * 备注
     */
    private String remark;



}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/LcpMetaComponent.java
package com.imyuanma.qingyun.lowcode.model;

import lombok.Data;
import java.util.Date;
import java.util.List;

import com.imyuanma.qingyun.interfaces.common.model.BaseDO;

/**
 * 组件元数据实体类
 *
 * @author YuanMaKeJi
 * @date 2022-12-03 21:44:59
 */
@Data
public class LcpMetaComponent extends BaseDO {

    /**
     * 主键
     */
    private Long id;

    /**
     * 组件图标
     */
    private String icon;

    /**
     * 组件code
     */
    private String code;

    /**
     * 组件名称
     */
    private String name;

    /**
     * 组件类型,base:基础组件,group:复合组件
     */
    private String type;

    /**
     * 分类
     */
    private String category;

    /**
     * 复合组件内容,当组件为复合组件时,组件模板以group_content为准
     */
    private String groupContent;
    /**
     * 是否可选
     */
    private String showInOptional;
    /**
     * 是否可作为父节点
     */
    private String canAsParent;

    /**
     * 备注
     */
    private String remark;

    /**
     * 属性配置集合
     */
    private List<LcpMetaComponentAttr> attrMetaList;



}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/LcpMetaComponentAttr.java
package com.imyuanma.qingyun.lowcode.model;

import lombok.Data;
import java.util.Date;
import com.imyuanma.qingyun.interfaces.common.model.BaseDO;

/**
 * 组件属性配置项实体类
 *
 * @author YuanMaKeJi
 * @date 2022-12-03 21:45:01
 */
@Data
public class LcpMetaComponentAttr extends BaseDO {

    /**
     * 主键
     */
    private Long id;

    /**
     * 属性名,例如:span
     */
    private String attrName;

    /**
     * 组件ID
     */
    private Long componentId;

    /**
     * 属性说明
     */
    private String attrText;

    /**
     * 属性默认值
     */
    private String attrDefault;

    /**
     * 属性数据类型,多个逗号拼接,var,string,number,boolean,object,array
     */
    private String attrDataType;

    /**
     * 是否支持vue绑定属性,yes/no
     */
    private String supportVueBind;

    /**
     * 备注
     */
    private String remark;



}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/SqlExecuteCmd.java
package com.imyuanma.qingyun.lowcode.model;

import com.imyuanma.qingyun.common.model.PageQuery;
import lombok.Data;

/**
 * sql执行
 *
 * @author wangjy
 * @date 2023/05/06 10:28:29
 */
@Data
public class SqlExecuteCmd {
    /**
     * 待执行sql
     */
    private String sql;
    /**
     * 分页查询参数 可以为空
     */
    private PageQuery pageQuery;
}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/bo/CheckRuleItem.java
package com.imyuanma.qingyun.lowcode.model.bo;

import com.imyuanma.qingyun.common.util.StringUtil;
import com.imyuanma.qingyun.lowcode.model.enums.ELcpFormControlCheckEnum;
import lombok.Data;

/**
 * 校验规则单项
 *
 * @author wangjy
 * @date 2022/04/02 10:59:09
 */
@Data
public class CheckRuleItem {
    /**
     * 校验类型
     *
     * @see ELcpFormControlCheckEnum
     */
    private String checkType;
    /**
     * 正则表达式
     */
    private String checkReg;
    /**
     * 错误提示
     */
    private String errorTips;
    /**
     * 最小值
     */
    private Integer min;
    /**
     * 最大值
     */
    private Integer max;

    /**
     * 构造校验项
     *
     * @param controlCheckEnum
     * @param fieldBO
     * @return
     */
    public static CheckRuleItem build(ELcpFormControlCheckEnum controlCheckEnum, GenerateFieldBO fieldBO) {
        CheckRuleItem checkRuleItem = new CheckRuleItem();
        checkRuleItem.setCheckType(controlCheckEnum.getType());
        String error;
        if (ELcpFormControlCheckEnum.ErrEmpty == controlCheckEnum) {
            error = String.format("%s不允许为空", StringUtil.getDefaultValue(fieldBO.getFormControlTitle(), fieldBO.getFieldDbRemark()));
        } else if (ELcpFormControlCheckEnum.ErrLength == controlCheckEnum) {
            checkRuleItem.setMin(1);
            checkRuleItem.setMax(fieldBO.getFieldDbLength());
            error = String.format("%s内容长度限制为%s~%s", StringUtil.getDefaultValue(fieldBO.getFormControlTitle(), fieldBO.getFieldDbRemark()), checkRuleItem.getMin(), checkRuleItem.getMax());
        } else if (ELcpFormControlCheckEnum.ErrNumber == controlCheckEnum) {
            error = String.format("%s请输入数字类型", StringUtil.getDefaultValue(fieldBO.getFormControlTitle(), fieldBO.getFieldDbRemark()));
        } else if (ELcpFormControlCheckEnum.ErrMail == controlCheckEnum) {
            error = String.format("%s请输入正确的邮箱格式", StringUtil.getDefaultValue(fieldBO.getFormControlTitle(), fieldBO.getFieldDbRemark()));
        } else if (ELcpFormControlCheckEnum.ErrPhone == controlCheckEnum) {
            error = String.format("%s请输入正确的手机号格式", StringUtil.getDefaultValue(fieldBO.getFormControlTitle(), fieldBO.getFieldDbRemark()));
        } else if (ELcpFormControlCheckEnum.ErrReg == controlCheckEnum) {
            error = String.format("%s请输入正确的手机号格式", StringUtil.getDefaultValue(fieldBO.getFormControlTitle(), fieldBO.getFieldDbRemark()));
        } else {
            error = "Error";
        }
        checkRuleItem.setErrorTips(error);
        return checkRuleItem;
    }


}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/bo/CssLinkBO.java
package com.imyuanma.qingyun.lowcode.model.bo;

import lombok.Data;

/**
 * css链接
 *
 * @author wangjy
 * @date 2022/07/29 22:31:44
 */
@Data
public class CssLinkBO {
    /**
     * 链接
     */
    private String url;

    public static CssLinkBO buildDefault() {
        CssLinkBO cssLinkBO = new CssLinkBO();
        cssLinkBO.setUrl("");
        return cssLinkBO;
    }
}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/bo/FieldSearchConfigBO.java
package com.imyuanma.qingyun.lowcode.model.bo;

import com.imyuanma.qingyun.common.util.CollectionUtil;
import com.imyuanma.qingyun.common.util.StringUtil;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;
import java.util.stream.Collectors;

/**
 * 字段查询配置
 *
 * @author wangjy
 * @date 2022/12/24 15:07:14
 */
@Data
public class FieldSearchConfigBO {
    /**
     * 根据哪些字段查询
     */
    private List<String> fieldJavaNameList = new ArrayList<>();
    /**
     * 单条查询, true表示根据字段查询单条, false表示根据字段查询多条数据
     */
    private Boolean selectOneFlag = true;

    /**
     * 查询字段集合, 生成代码时使用, 配置时不用
     */
    private List<GenerateFieldBO> fieldList;

    /**
     * db字段名拼接
     *
     * @return
     */
    public String getFieldDbNameJoinStr() {
        if (CollectionUtil.isNotEmpty(fieldList)) {
            return fieldList.stream().map(GenerateFieldBO::getFieldDbName).collect(Collectors.joining(","));
        }
        return null;
    }

    /**
     * java字段名拼接
     *
     * @return
     */
    public String getFieldJavaNameJoinStr() {
        if (CollectionUtil.isNotEmpty(fieldList)) {
            return fieldList.stream().map(GenerateFieldBO::getFieldJavaName).collect(Collectors.joining(","));
        }
        return null;
    }

    /**
     * 方法名
     *
     * @return
     */
    public String getMethodName() {
        if (CollectionUtil.isNotEmpty(fieldList)) {
            StringBuilder sb = new StringBuilder(Boolean.TRUE.equals(selectOneFlag) ? "getBy" : "getListBy");
            for (GenerateFieldBO fieldBO : fieldList) {
                sb.append(StringUtil.toFirstUpper(fieldBO.getFieldJavaName()));
            }
            return sb.toString();
        }
        return null;
    }

    /**
     * 转换为代码生成时配置
     *
     * @param fieldList
     * @return
     */
    public FieldSearchConfigBO convertForGen(List<GenerateFieldBO> fieldList) {
        FieldSearchConfigBO fieldSearchConfigBO = new FieldSearchConfigBO();
        fieldSearchConfigBO.setFieldJavaNameList(fieldList.stream().map(GenerateFieldBO::getFieldJavaName).collect(Collectors.toList()));
        fieldSearchConfigBO.setSelectOneFlag(this.selectOneFlag);
        fieldSearchConfigBO.setFieldList(fieldList);
        return fieldSearchConfigBO;
    }

    /**
     * 是否有效
     *
     * @return
     */
    public boolean valid() {
        return selectOneFlag != null && CollectionUtil.isNotEmpty(fieldJavaNameList);
    }

    /**
     * 是否有效for生成代码
     *
     * @return
     */
    public boolean genValid() {
        return selectOneFlag != null && CollectionUtil.isNotEmpty(fieldList);
    }

}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/bo/GenerateButtonBarConfigBO.java
package com.imyuanma.qingyun.lowcode.model.bo;

import com.imyuanma.qingyun.lowcode.model.enums.ELcpInnerButtonEnum;
import lombok.Data;

import java.util.ArrayList;
import java.util.List;

/**
 * 按钮栏配置
 *
 * @author wangjy
 * @date 2022/07/03 12:13:50
 */
@Data
public class GenerateButtonBarConfigBO {
    /**
     * 按钮集合
     *
     * @see ELcpInnerButtonEnum 内置按钮, 除此之外还支持自定义按钮
     */
    private List<LcpButtonBO> buttonList;

    /**
     * 按钮栏长度预估
     *
     * @return
     */
    public int getButtonBarWidth() {
        int len = 10;
        if (this.buttonList != null) {
            for (LcpButtonBO buttonBO : this.buttonList) {
                // 大按钮加宽10, 链接按钮减少20
                int ext = ("large".equals(buttonBO.getSize()) ? 10 : 0) + ("link".equals(buttonBO.getCategory()) ? -20 : 0);
                // 默认按钮按照74计算, 再加上不同按钮的弹性
                len += 74 + ext;
                // 超出的字数每个字按14计算
                if (buttonBO.getName() != null && buttonBO.getName().length() > 2) {
                    len += (buttonBO.getName().length() - 2) * 14;
                }
            }
        }
        return len;
    }

    /**
     * 添加按钮
     *
     * @param buttonBO
     */
    public void addButton(LcpButtonBO buttonBO) {
        if (this.buttonList == null) {
            this.buttonList = new ArrayList<>();
        }
        this.buttonList.add(buttonBO);
    }

    /**
     * 初始化按钮栏对象, 赋值默认值, 表面存在null引起页面错误
     *
     * @return
     */
    public static GenerateButtonBarConfigBO newInstance() {
        GenerateButtonBarConfigBO configBO = new GenerateButtonBarConfigBO();
        configBO.buttonList = new ArrayList<>();
        return configBO;
    }

}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/bo/GenerateControlCheckRuleBO.java
package com.imyuanma.qingyun.lowcode.model.bo;

import lombok.Data;

import java.util.List;

/**
 * 表单项校验规则
 *
 * @author wangjy
 * @date 2022/05/04 17:48:20
 */
@Data
public class GenerateControlCheckRuleBO {
    /**
     * 表单校验
     */
    private List<CheckRuleItem> checkRuleList;
}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/bo/GenerateControlConfigBO.java
package com.imyuanma.qingyun.lowcode.model.bo;

import com.imyuanma.qingyun.common.util.StringUtil;
import lombok.Data;

/**
 * 表单项其他配置
 *
 * @author wangjy
 * @date 2022/05/04 17:46:48
 */
@Data
public class GenerateControlConfigBO {
    /**
     * 最小值
     */
    private Long min;
    /**
     * 最大值
     */
    private Long max;
    /**
     * 步长
     */
    private Long step;
    /**
     * 数字输入控件是否展示控制按钮(加减按钮)
     * 默认不要
     */
    private Integer numberControls;

    /**
     * 行数
     */
    private Integer rows;
    /**
     * 自适应文本域 1/0
     */
    private Integer autosize;

    /**
     * 选中值
     */
    private String yesValue;
    /**
     * 未选中值
     */
    private String noValue;
    /**
     * 选中文案
     */
    private String yesText;
    /**
     * 未选中文案
     */
    private String noText;

    /**
     * 树选择支持选择任意节点, 1表示可以选择任意节点, 0表示只可以选择叶子节点
     */
    private Integer treeSupportCheckAny;
    /**
     * 子节点数据的字段名
     * 例如: 树组件, 树表格, 树选择等有子节点的组件用
     */
    private String childrenField;
    /**
     * 数据表格自定义格式化代码
     */
    private String listValueFormatHtml = "";

    // ==============文件上传 start==============
    /**
     * 上传存储策略 fs:本地存储 cos:腾讯对象存储cos
     */
    private String uploadStorage = "fs";
    /**
     * 上传地址
     */
    private String uploadUrl = "";
    /**
     * COS临时签名
     */
    private String cosStsUrl = "";
    /**
     * COS分桶
     */
    private String cosBucket = "";
    /**
     * COS区域
     */
    private String cosRegion = "";
    /**
     * 上传文件夹ID
     */
    private String uploadFolderId = "";
    /**
     * 上传组件参数绑定的字段
     * path: 文件url
     */
    private String uploadBindAttr = "";

    /**
     * 判断是否使用cos存储
     * @return
     */
    public boolean useCosStorage() {
        return "cos".equals(this.uploadStorage);
    }

    /**
     * 上传组件配置的属性值
     *
     * @return
     */
    public String buildUploadAttrHtml() {
        StringBuilder sb = new StringBuilder("");
        sb.append(eleAttrHtml("folder-id", this.uploadFolderId));
        sb.append(eleAttrHtml("storage", this.uploadStorage));
        sb.append(eleAttrHtml("bind-file-attr", this.uploadBindAttr));
        if (this.useCosStorage()) {
            sb.append(eleAttrHtml("cos-sts-url", this.cosStsUrl));
            sb.append(eleAttrHtml("cos-bucket", this.cosBucket));
            sb.append(eleAttrHtml("cos-region", this.cosRegion));
        } else {
            sb.append(eleAttrHtml("url", this.uploadUrl));
        }
        return sb.toString();
    }

    private String eleAttrHtml(String attr, String value) {
        return StringUtil.isNotBlank(value) ? String.format(" %s=\"%s\"", attr, value) : "";
    }
    // ==============文件上传 end==============


    // ==============md编辑器 start==============
    /**
     * 编辑器高度
     */
    private String editorMdHeight = "";
    /**
     * 编辑器工具栏, 具体枚举值参考组件代码
     */
    private String editorMdToolbar = "default";
    /**
     * 编辑器html代码绑定变量
     */
    private String editorHtmlBind = "";
    // ==============md编辑器 end==============

}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/bo/GenerateControlDataSourceBO.java
package com.imyuanma.qingyun.lowcode.model.bo;

import com.imyuanma.qingyun.lowcode.model.enums.ELcpFormItemDataSourceTypeEnum;
import lombok.Data;

import java.util.List;

/**
 * 表单控件数据源配置
 *
 * @author wangjy
 * @date 2022/05/04 17:47:43
 */
@Data
public class GenerateControlDataSourceBO {
    /**
     * 数据类型
     * no,static,url,dict
     * @see ELcpFormItemDataSourceTypeEnum
     */
    private String dataType;
    /**
     * 字典code
     */
    private String dictCode;
    /**
     * 数据查询地址
     */
    private String dataUrl;
    /**
     * 值字段
     */
    private String keyField;
    /**
     * 文本字段
     */
    private String valueField;
    /**
     * static静态数据选项集合
     */
    private List<OptionItem> optionItemList;

    /**
     * 数据源配置是否有效
     * @return
     */
    public boolean isValid() {
        ELcpFormItemDataSourceTypeEnum typeEnum = ELcpFormItemDataSourceTypeEnum.of(this.dataType);
        return typeEnum != null && typeEnum != ELcpFormItemDataSourceTypeEnum.NO;
    }

}

qingyun-lowcode/src/main/java/com/imyuanma/qingyun/lowcode/model/bo/JsLinkBO.java
package com.imyuanma.qingyun.lowcode.model.bo;

import lombok.Data;

/**
 * js链接
 *
 * @author wangjy
 * @date 2022/07/29 22:31:44
 */
@Data
public class JsLinkBO {
    /**
     * 链接
     */
    private String url;

    public static JsLinkBO buildDefault() {
        JsLinkBO jsLinkBO = new JsLinkBO();
        jsLinkBO.setUrl("");
        return jsLinkBO;
    }
}

qingyun-lowcode/src/main/resources/com/imyuanma/qingyun/lowcode/template/v4/Dao.ftl
package ${model.packagePath}.${model.moduleName}.dao;

import com.imyuanma.qingyun.common.model.PageQuery;
<#if model.supportTraceAll>
import com.imyuanma.qingyun.interfaces.monitor.annotation.Trace;
</#if>
import ${model.packagePath}.${model.moduleName}.model.${model.className};
import org.apache.ibatis.annotations.Mapper;
import org.apache.ibatis.annotations.Param;

import java.util.List;

/**
 * ${model.name!}dao
 *
 * @author ${model.author!}
 * @date ${nowTimeStr}
 */
@Mapper
public interface I${model.className}Dao {

    /**
     * 列表查询
     *
     * @param ${model.className?uncap_first} 查询条件
     * @return
     */
<#if model.supportTraceAll>
    @Trace("查询${model.name!}列表")
</#if>
    List<${model.className}> getList(${model.className} ${model.className?uncap_first});

    /**
     * 分页查询
     *
     * @param ${model.className?uncap_first} 查询条件
     * @param pageQuery 分页参数
     * @return
     */
<#if model.supportTraceAll>
    @Trace("分页查询${model.name!}")
</#if>
    List<${model.className}> getList(${model.className} ${model.className?uncap_first}, PageQuery pageQuery);

    /**
     * 统计数量
     *
     * @param ${model.className?uncap_first} 查询条件
     * @return
     */
<#if model.supportTraceAll>
    @Trace("统计${model.name!}数量")
</#if>
    int count(${model.className} ${model.className?uncap_first});

    /**
     * 主键查询
     *
     * @param id 主键
     * @return
     */
<#if model.supportTraceAll>
    @Trace("主键查询${model.name!}")
</#if>
    ${model.className} get(${primaryKeyJavaType} id);

    /**
     * 主键批量查询
     *
     * @param list 主键集合
     * @return
     */
<#if model.supportTraceAll>
    @Trace("主键批量查询${model.name!}")
</#if>
    List<${model.className}> getListByIds(List<${primaryKeyJavaType}> list);
<#list fieldSearchConfigList as item>

    /**
     * 根据${item.fieldJavaNameJoinStr}查询
     *
<#list item.fieldList as field>
     * @param ${field.fieldJavaName} ${field.fieldDbRemark}
</#list>
     * @return
     */
<#if model.supportTraceAll>
    @Trace("根据${item.fieldJavaNameJoinStr}查询${model.name!}")
</#if>
    <#if !item.selectOneFlag>List${"<"}</#if>${model.className}<#if !item.selectOneFlag>${">"}</#if> ${item.methodName}(<#list item.fieldList as field><#if (field_index > 0)>, </#if>@Param("${field.fieldJavaName}") ${field.fieldJavaType} ${field.fieldJavaName}</#list>);
</#list>

    /**
     * 插入
     *
     * @param ${model.className?uncap_first} 参数
     * @return
     */
<#if model.supportTraceAll>
    @Trace("插入${model.name!}")
</#if>
    int insert(${model.className} ${model.className?uncap_first});

    /**
     * 选择性插入
     *
     * @param ${model.className?uncap_first} 参数
     * @return
     */
<#if model.supportTraceAll>
    @Trace("选择性插入${model.name!}")
</#if>
    int insertSelective(${model.className} ${model.className?uncap_first});

    /**
     * 批量插入
     *
     * @param list 参数
     * @return
     */
<#if model.supportTraceAll>
    @Trace("批量插入${model.name!}")
</#if>
    int batchInsert(List<${model.className}> list);

    /**
     * 批量选择性插入
     *
     * @param list 参数
     * @return
     */
<#if model.supportTraceAll>
    @Trace("批量选择性插入${model.name!}")
</#if>
    int batchInsertSelective(List<${model.className}> list);

    /**
     * 修改
     *
     * @param ${model.className?uncap_first} 参数
     * @return
     */
<#if model.supportTraceAll>
    @Trace("修改${model.name!}")
</#if>
    int update(${model.className} ${model.className?uncap_first});

    /**
     * 选择性修改
     *
     * @param ${model.className?uncap_first} 参数
     * @return
     */
<#if model.supportTraceAll>
    @Trace("选择性修改${model.name!}")
</#if>
    int updateSelective(${model.className} ${model.className?uncap_first});

    /**
     * 批量修改某字段
     *
     * @param idList      主键集合
     * @param fieldDbName 待修改的字段名
     * @param fieldValue  修改后的值
     * @return
     */
<#if model.supportTraceAll>
    @Trace("批量修改${model.name!}属性")
</#if>
    int batchUpdateColumn(@Param("idList") List<${primaryKeyJavaType}> idList, @Param("fieldDbName") String fieldDbName, @Param("fieldValue") Object fieldValue);

    /**
     * 删除
     *
     * @param id 主键
     * @return
     */
<#if model.supportTraceAll>
    @Trace("删除${model.name!}")
</#if>
    int delete(${primaryKeyJavaType} id);

    /**
     * 批量删除
     *
     * @param list 主键集合
     * @return
     */
<#if model.supportTraceAll>
    @Trace("批量删除${model.name!}")
</#if>
    int batchDelete(List<${primaryKeyJavaType}> list);

    /**
     * 条件删除(默认和getList方法的条件相同)
     *
     * @param ${model.className?uncap_first} 参数
     * @return
     */
<#if model.supportTraceAll>
    @Trace("条件删除${model.name!}")
</#if>
    int deleteByCondition(${model.className} ${model.className?uncap_first});

    /**
     * 删除全部
     *
     * @return
     */
<#if model.supportTraceAll>
    @Trace("全量删除${model.name!}")
</#if>
    int deleteAll();

}

qingyun-lowcode/src/main/resources/com/imyuanma/qingyun/lowcode/template/v4/Enum.ftl
package ${model.packagePath}.${model.moduleName}.model.enums;
<#assign enumClassName = "E" + model.className + enumFieldNameUpperFirst + "Enum" />

/**
 * ${enumField.formControlTitle!}枚举
 *
 * @author ${model.author!}
 * @date ${nowTimeStr}
 */
public enum ${enumClassName} {
<#if enumField.numberFlag>
    <#list enumOptionList as option>
    CODE_${option.key}(${option.key}, "${option.value}"),
    </#list>
<#else>
    <#list enumOptionList as option>
    CODE_${option.key}("${option.key}", "${option.value}"),
    </#list>
</#if>
    ;

    /**
     * code
     */
    private ${enumField.fieldJavaType} code;
    /**
     * 文案
     */
    private String text;

    ${enumClassName}(${enumField.fieldJavaType} code, String text) {
        this.code = code;
        this.text = text;
    }

    /**
     * 根据code获取枚举
     *
     * @param code code值
     */
    public static ${enumClassName} getByCode(${enumField.fieldJavaType} code) {
        for (${enumClassName} e : ${enumClassName}.values()) {
            if (e.code != null && e.code.equals(code)) {
                return e;
            }
        }
        return null;
    }

    public ${enumField.fieldJavaType} getCode() {
        return code;
    }

    public String getText() {
        return text;
    }
}